Repository magento/magento-cloud-patches, pull requests merged in 2019-11, with the labels that each got.

#4 MAGECLOUD-4448-4449: Deliver core patches
  composer.json
  patches.json
  patches/MC-21696__fix_broken_pagination_on_ES6__2.3.3.patch
  patches/MC-21820__fix_broken_method_chaining__2.3.3.patch
Labels: Release: 1.0.0, aproved

#5 MAGECLOUD-4585: Reduce q-ty of Reports Created in /app/*/var/report
  patches.json
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.17.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.4.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.1.8.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.0.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.5.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.6.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.2.8.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.0.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.1.patch
  patches/MAGECLOUD-3392__reduce_q-ty_of_error_report_files__2.3.2.patch
  patches/MAGECLOUD-4407__fix_namespace_vertex_tax__3.2.0.patch
Labels: Release: 1.0.0, aproved

#6 MAGECLOUD-4649: Merge PageBuilder Security Patches to m-cloud-patches
  patches.json
  patches/MDVA-22979__fix_pagebuilder_module__2.3.1.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.2.patch
Labels: Release: 1.0.0, review

#7 MAGECLOUD-4661: Security-only Releases Broke Cloud Patching Process
  patches.json
  patches/MAGECLOUD-1582__fix_session_manager_locking__2.2.0.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.1.13.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.1.14.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.1.4.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.1.5.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.2.0.patch
  patches/MAGECLOUD-1607__overhaul_cron_implementation__2.2.2.patch
  patches/MAGECLOUD-1736__respect_minification_override__2.1.4.patch
  patches/MAGECLOUD-1736__respect_minification_override__2.2.0.patch
  patches/MAGECLOUD-2033__prevent_deadlock_during_db_dump__2.2.0.patch
  patches/MAGECLOUD-2159__unlock_locale_editing_when_scd_on_demand__2.2.0.patch
  patches/MAGECLOUD-2445__do_not_run_cron_when_it_is_disabled__2.1.4.patch
  patches/MAGECLOUD-2573__installation_without_admin_creation__2.2.2.patch
  patches/MAGECLOUD-2793__fix_monolog_slack_handler_2.1.x.patch
  patches/MAGECLOUD-2850_fix_amazon_payment_module__2.2.6.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.2.0.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.2.4.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.3.0.patch
  patches/MAGECLOUD-3611__multi_thread_scd__2.3.2.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.3.0.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.3.1.patch
  patches/MAGECLOUD-4442__fix_backward_compatibility_of_new_mail_interfaces__2.3.3.patch
  patches/MAGETWO-45357__avoid_nonexistent_setup_area__2.1.4.patch
  patches/MAGETWO-57413__move_vendor_path_autoloader__2.1.4.patch
  patches/MAGETWO-57414__load_static_assets_without_rewrites__2.1.17.patch
  patches/MAGETWO-57414__load_static_assets_without_rewrites__2.1.4.patch
  patches/MAGETWO-62660__prevent_excessive_js_optimization__2.1.4.patch
  patches/MAGETWO-67097__fix_credis_pipeline_bug__2.1.4.patch
  patches/MAGETWO-67805__fix_image_resizing_after_upgrade__2.1.6.patch
  patches/MAGETWO-69847__support_credis_forking_during_scd__2.1.4.patch
  patches/MAGETWO-69847__support_credis_forking_during_scd__2.2.0.patch
  patches/MAGETWO-84444__fix_mview_on_staging__2.1.10.patch
  patches/MAGETWO-84444__fix_mview_on_staging__2.1.4.patch
  patches/MAGETWO-84444__fix_mview_on_staging__2.1.5.patch
  patches/MAGETWO-98833__turn_off_google_chart_api__2.x.patch
  patches/MC-5964__preauth_sql__2.2.0.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.1.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.2.patch
  patches/MDVA-8695__properly_encode_characters_in_emails__2.1.4.patch
  patches/SET-36__fix_oom_during_customer_import__2.1.11.patch
  patches/SET-36__fix_oom_during_customer_import__2.1.4.patch
  patches/SET-36__fix_oom_during_customer_import__2.2.0.patch
  patches/SET-36__fix_oom_during_customer_import__2.2.4.patch
Labels: aproved
