Repository magento/magento-cloud-patches, pull requests merged in 2020-02, with the labels that each got.

#20 MAGECLOUD-5215: Forward-port delivered changes
  composer.json
  patches.json
  patches/MAGECLOUD-1601__trim_static_content_path__2.1.4.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.10.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.5.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.9.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.0.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.1.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.2.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.3.patch
Labels: aproved

#21 MC-31387: Paypal issue with region on 2.3.4
  patches.json
  patches/MC-31387__fix_paypal_issue_with_region__2.3.4.patch
Labels: Release: 1.0.2, aproved

#22 Back-port develop into 1.0
  composer.json
  config/services.xml
  patches.json
  patches/MC-31387__fix_paypal_issue_with_region__2.3.4.patch
  src/Shell/PackageNotFoundException.php
  src/Shell/ProcessFactory.php
Labels: aproved

#23 Remove conflict from composer.json
  composer.json
Labels: aproved

#24 Deliver 1.0 fix
  composer.json
Labels: aproved

#25 Fix JSON syntax error on Magento_Amqp patches
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.1.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.2.patch
Labels: Release: 1.0.2, aproved

#26 MAGECLOUD-5359: Patches 1.0.2 fail on magento version 2.1.4 with php 7.0
  composer.json
Labels: 1.0, Release: 1.0.2, aproved, release-note-needed

#28 MAGECLOUD-5323: Update Cloud projects with proper licenses
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: aproved

#27 MAGECLOUD-5069: FPC is getting disabled during deployments
  patches.json
  patches/MAGECLOUD-5069__fpc_is_getting_disabled_during_deployments__2.3.2.patch
Labels: Release: 1.0.3, aproved
