Repository magento/magento-cloud-patches, pull requests merged in 2020-04, with the labels that each got.

#33 MCLOUD-5620: Increase coverage for patches
  .travis.yml
  src/Test/Functional/Acceptance/Acceptance71CeCest.php
  src/Test/Functional/Acceptance/Acceptance71Cest.php
  src/Test/Functional/Acceptance/Acceptance72CeCest.php
  src/Test/Functional/Acceptance/Acceptance72Cest.php
  src/Test/Functional/Acceptance/AcceptanceCeCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  tests/travis/functional-ce.sh
  tests/travis/functional-ee.sh
Labels: Progress: review

#35 MCLOUD-5701 / MCLOUD-5375: Fix cloud patches
  patches.json
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.5_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.5_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.6_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.6_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.7_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.7_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.8_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.8_ee.patch
Labels: Progress: approved, Release: 1.0.4

#34 MCLOUD-5666: Assign every patch to modules it changes
  patches.json
  patches/MAGETWO-53941__fix_enterprise_braintree_code__100.1.6.patch
  patches/MAGETWO-53941__fix_enterprise_payment_codes__2.1.8.patch
  patches/MAGETWO-53941__fix_enterprise_paypal_codes__100.1.6.patch
  patches/MAGETWO-98129__transaction_field_is_removed_by_authorize_net__100.2.0.patch
  patches/MC-31387__fix_paypal_issue_with_region__100.3.4.patch
Labels: 1.0, Progress: approved, Progress: qa in progress, Release: 1.0.4

#38 Forward-port 1.0 branch
  composer.json
  patches.json
  patches/MAGECLOUD-5069__fpc_is_getting_disabled_during_deployments__2.3.5.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.1.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.2.patch
Labels: Progress: approved

#36 MCLOUD-5650: Magento\Framework\App\DeploymentConfig\Reader::load function is taking too much time
  patches.json
  patches/MCLOUD-5650__hold_deployment_config_after_reading_from_file.patch
Labels: Progress: approved, Release: 1.0.4

#40 MCLOUD-5684: Pagination Not working - product_list_limit=all
  patches.json
  patches/MCLOUD-5684__pagination_not_working_product_list_limit_all__2.3.2.patch
  patches/MCLOUD-5684__pagination_not_working_product_list_limit_all__2.3.4.patch
Labels: 1.0, Progress: approved, Release: 1.0.4

#39 MCLOUD-3025: Sitemap generation warnings
  patches.json
  patches/MCLOUD-3025__sitemap_generation_warnings__2.3.0.patch
  patches/MCLOUD-3025__sitemap_generation_warnings__2.3.3.patch
Labels: Progress: approved, Release: 1.0.4
