Repository magento/magento-cloud-patches, pull requests merged in 2020-08, with the labels that each got.

#71 MCLOUD-6651: Remove FPC patch for Magento 2.2.6
  patches.json
Labels: Progress: ready for testing, Release Line: 1.0, Release: 1.0.6

#74 MCLOUD-6659: Update Redis L2 cache patch
  patches.json
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.0.patch
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.1.patch
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.2.patch
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.3-p1.patch
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.3.patch
  patches/MCLOUD-6139_MCLOUD-6211__redis_improvement_patches__2.3.4.patch
  patches/MCLOUD-6211__redis_improvement_patches__2.3.5.patch
  patches/MCLOUD-6659__fix_L2_redis_cache__2.4.0.patch
  src/Test/Functional/Acceptance/AcceptanceCest.php
Labels: Progress: ready for delivery, Release: 1.0.7

#64 BUNDLE-2683: VBE Braintree - Error occurs in Admin Braintree Settlement Report
  patches.json
  patches/BUNDLE-2683__braintree_settlement_report_fix__4.1.0.patch
Labels: Progress: approved, Release: 1.0.7
