Repository magento/magento-cloud-patches, pull requests merged in 2020-06, with the labels that each got.

#46 MCLOUD-5953: Backport Redis patches
  patches.json
  patches/MDVA-22950__large_amount_of_keys_block_cache__2.3.1.patch
  patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
  patches/MDVA-27538__fix_performance_issue_in_cache_locking_mechanism__2.3.3-p1.patch
  patches/MDVA-27538__fix_performance_issue_in_cache_locking_mechanism__2.3.3.patch
  src/Test/Functional/Acceptance/AbstractCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/PatchApplierCest.php
  tests/functional/_data/files/patches/patch.patch
  tests/functional/_data/files/patches/target_file.md
  tests/functional/_data/files/patches/target_file_applied_patch.md
Labels: Progress: approved, Progress: review, Release: 1.0.5

#48 MAGECLOUD-6029: Implement New Relic Logs in Context
  patches.json
  patches/MAGECLOUD-6029__add_processor_interface_2.1.x.patch
Labels: Progress: approved, Release: 1.0.5

#50 Add doc requirements to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Progress: review

#53 Merge develop into 1.0
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1.0, Release: 1.0.5

#54 Bump version
  composer.json
Labels: Progress: approved
