Repository magento/magento-cloud-patches, pull requests merged in 2020-05, with the labels that each got.

#43 Backport develop branch
  .gitignore
  .travis.yml
  codeception.dist.yml
  composer.json
  patches.json
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.5_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.5_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.6_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.6_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.7_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.7_ee.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.8_ce.patch
  patches/MAGECLOUD-3913__fix_problems_with_consumer_runners_on_cloud_clusters__2.2.8_ee.patch
  patches/MAGETWO-53941__fix_enterprise_braintree_code__100.1.6.patch
  patches/MAGETWO-53941__fix_enterprise_payment_codes__2.1.8.patch
  patches/MAGETWO-53941__fix_enterprise_paypal_codes__100.1.6.patch
  patches/MAGETWO-98129__transaction_field_is_removed_by_authorize_net__100.2.0.patch
  patches/MC-31387__fix_paypal_issue_with_region__100.3.4.patch
  patches/MCLOUD-3025__sitemap_generation_warnings__2.3.0.patch
  patches/MCLOUD-3025__sitemap_generation_warnings__2.3.3.patch
  patches/MCLOUD-5650__hold_deployment_config_after_reading_from_file.patch
  patches/MCLOUD-5684__pagination_not_working_product_list_limit_all__2.3.2.patch
  patches/MCLOUD-5684__pagination_not_working_product_list_limit_all__2.3.4.patch
  src/Test/Functional/Acceptance.suite.dist.yml
  src/Test/Functional/Acceptance/Acceptance71CeCest.php
  src/Test/Functional/Acceptance/Acceptance71Cest.php
  src/Test/Functional/Acceptance/Acceptance72CeCest.php
  src/Test/Functional/Acceptance/Acceptance72Cest.php
  src/Test/Functional/Acceptance/AcceptanceCeCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  tests/functional/_data/.gitkeep
  tests/functional/_data/files/debug_logging/.magento.env.yaml
  tests/functional/_output/.gitignore
  tests/travis/functional-ce.sh
  tests/travis/functional-ee.sh
  tests/travis/static-unit.sh
Labels: 1.0, Progress: approved, Release: 1.0.4

#41 MCLOUD-5837: HA load balancer issues
  patches.json
  patches/MCLOUD-5837__fix_filesystem_load_balancer_issue__2.3.4.patch
Labels: 1.0, Progress: approved, Release: 1.0.4

#42 MCLOUD-5930: BUNDLE-2554: [Amazon Pay] Unable to switch credit card during checkout
  patches.json
  patches/BUNDLE-2554__set_payment_info_bug_fix__3.4.1.patch
Labels: 1.0, Progress: approved, Release: 1.0.4, release-note-completed

#45 MCLOUD-5914: Release Cloud Patches 1.0.4
  composer.json
Labels: 1.0, Release: 1.0.4

#47 Forward-port 1.0 branch
  composer.json
  patches.json
  patches/BUNDLE-2554__set_payment_info_bug_fix__3.4.1.patch
  patches/MCLOUD-5837__fix_filesystem_load_balancer_issue__2.3.4.patch
Labels: Progress: approved
