Repository magento/magento-cloud-patches, pull requests merged in 2020-01, with the labels that each got.

#8 MAGECLOUD-4606: Review Hotfixes List and Add All Missing for 2.1.4+
  patches.json
  patches/MAGETWO-92926__fix_for_multi-site_configuration_issue__2.2.4.patch
  patches/MAGETWO-93036__cannot_change_the_applied_theme__2.2.5.patch
  patches/MAGETWO-93083__optimize_retrieving_product_attributes__2.2.5.patch
  patches/MAGETWO-95591__customer_attributes_issue__2.2.6.patch
  patches/MAGETWO-98129__transaction_field_is_removed_by_authorize_net__2.2.0.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.1.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.2.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.2.0.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.2.7.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.3.0.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.1.4.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.2.0.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.3.0.patch
Labels: Release: 1.0.1, aproved

#10 MAGECLOUD-4847: Issues caused by MC-21696 hot fix from ece-tools patches
  patches.json
  patches/MAGECLOUD-4847__elasticsearch_and_products_display_fix__2.3.3.patch
  patches/MC-21696__fix_broken_pagination_on_ES6__2.3.3.patch
Labels: Release: 1.0.1, aproved

#11 MAGECLOUD-4884: Update PageBuilder Patches for RCE
  patches.json
  patches/MDVA-22979__fix_pagebuilder_module__2.3.1.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.2.patch
  patches/PB-319__fix_pagebuilder_module__2.3.1.patch
  patches/PB-320__fix_pagebuilder_module__2.3.2.patch
  patches/PB-322__fix_pagebuilder_module__2.3.2-p1.patch
  patches/PB-323__fix_pagebuilder_module__2.3.3.patch
Labels: Release: 1.0.1, aproved

#12 Merge develop into 1.0
  patches.json
  patches/MAGECLOUD-4847__elasticsearch_and_products_display_fix__2.3.3.patch
  patches/MAGETWO-92926__fix_for_multi-site_configuration_issue__2.2.4.patch
  patches/MAGETWO-93036__cannot_change_the_applied_theme__2.2.5.patch
  patches/MAGETWO-93083__optimize_retrieving_product_attributes__2.2.5.patch
  patches/MAGETWO-95591__customer_attributes_issue__2.2.6.patch
  patches/MAGETWO-98129__transaction_field_is_removed_by_authorize_net__2.2.0.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.1.patch
  patches/MAGETWO-99902__pass_store_view_scope_in_async_web_api__2.3.2.patch
  patches/MC-21696__fix_broken_pagination_on_ES6__2.3.3.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.1.patch
  patches/MDVA-22979__fix_pagebuilder_module__2.3.2.patch
  patches/PB-319__fix_pagebuilder_module__2.3.1.patch
  patches/PB-320__fix_pagebuilder_module__2.3.2.patch
  patches/PB-322__fix_pagebuilder_module__2.3.2-p1.patch
  patches/PB-323__fix_pagebuilder_module__2.3.3.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.2.0.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.2.7.patch
  patches/PRODSECBUG-2233__fix_xss_in_order_history__2.3.0.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.1.4.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.2.0.patch
  patches/PRODSECBUG-2432__admin_path_disclosure_bug__2.3.0.patch
  src/Command/Patch/Manager.php
  src/Test/Unit/Command/Patch/ManagerTest.php
Labels: 1.0, Release: 1.0.1, aproved

#14 MAGECLOUD-4980: Pagebuilder patches fail CE functional tests
  patches.json
Labels: 1.0, Release: 1.0.1, aproved

#15 MAGECLOUD-4982: De-composed magento-cloud-patches fail to apply locally
  patches.json
  patches/MAGECLOUD-1601__trim_static_content_path__2.1.4.patch
Labels: 1.0, aproved

#16 MAGECLOUD-4979: Cleanup Composer Dependencies
  composer.json
Labels: Release: 1.0.1, aproved

#17 MAGECLOUD-4530: Create patch for deadlocks related to crons / consumers
  patches.json
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.10.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.5.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.2.9.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.0.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.1.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.2.patch
  patches/MAGECLOUD-4530__fix_cron_deadlocks_and_improve_job_locking__2.3.3.patch
Labels: qa

#18 Bump Composer version to 1.0.1
  composer.json
Labels: review

#19 MAGECLOUD-5127: Update Constraints for Magento 2.4
  composer.json
  config/services.xml
  src/Shell/PackageNotFoundException.php
  src/Shell/ProcessFactory.php
Labels: Release: 1.0.2, aproved
